//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAssign
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public int EmployeePhone { get; set; }
        public int ReastaurantId { get; set; }
        public string ReastaurantName { get; set; }
        public string ReastaurantAddress { get; set; }
        public int ReastaurantPhone { get; set; }
        public string ReastaurantEmail { get; set; }
        public string FoodQuantity { get; set; }
    }
}
